// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GovUKCarTaxTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void govUKCarTax() {
    // Test name: GovUKCarTax
    // Step # | name | target | value
    // 1 | open | https://www.gov.uk/ | 
    driver.get("https://www.gov.uk/");
    // 2 | setWindowSize | 1171x802 | 
    driver.manage().window().setSize(new Dimension(1171, 802));
    // 3 | click | id=search-main-206d7ca9 | 
    driver.findElement(By.cssSelector("search-main-206d7ca9")).click();
    // 4 | type | id=search-main-206d7ca9 | car tax
    driver.findElement(By.id("search-main-206d7ca9")).sendKeys("car tax");
    // 5 | click | css=.govuk-\!-margin-bottom-0 .gem-c-search__submit | 
    driver.findElement(By.cssSelector(".govuk-\\!-margin-bottom-0 .gem-c-search__submit")).click();
    // 6 | click | linkText=Tax your vehicle | 
    driver.findElement(By.linkText("Tax your vehicle")).click();
  }
}
