// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TodoE2ETest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void todoE2E() {
    // Test name: TodoE2E
    // Step # | name | target | value
    // 1 | open | https://todomvc.com/ | 
    driver.get("https://todomvc.com/");
    // 2 | setWindowSize | 1171x802 | 
    driver.manage().window().setSize(new Dimension(1171, 802));
    // 3 | click | linkText=React | 
    driver.findElement(By.linkText("React")).click();
    // 4 | type | css=.new-todo | Buy some milk
    driver.findElement(By.cssSelector(".new-todo")).sendKeys("Buy some milk");
    // 5 | sendKeys | css=.new-todo | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".new-todo")).sendKeys(Keys.ENTER);
    // 6 | click | css=.toggle | 
    driver.findElement(By.cssSelector(".toggle")).click();
  }
}
